interface MainInfo {
  title: string;
  name: string;
  email: string;
}

interface Socials {
  github: string;
  linkedin: string;
  stackoverflow: string;
}

interface Homepage {
  title: string;
  description: string;
}

interface About {
  title: string;
  description: string;
}

interface Project {
  title: string;
  description: string;
  logo: string;
  linkText: string;
  link: string;
}

interface Data {
  main: MainInfo;
  socials: Socials;
  homepage: Homepage;
  about: About;
  projects: Project[];
}

const DATA: Data = {
  main: {
    title: "Moritz Reis | Portfolio",
    name: "Moritz Reis",
    email: "me@moritzreis.dev",
  },

  socials: {
    github: "https://github.com/clFaster",
    linkedin: "https://www.linkedin.com/in/moritzreis/",
    stackoverflow: "https://stackoverflow.com/users/8307815",
  },

  homepage: {
    title: "Software Architect building scalable systems",
    description:
      "Hey there! I'm a software architect with a love for ASP.NET, C#, and more. Currently designing and building scalable systems at SIMStation in Vienna. I enjoy turning messy problems into clear, reliable architectures, mentoring teams, and shipping software that's secure, maintainable, and actually pleasant to work with.",
  },

  about: {
    title:
      "I’m Moritz. I live in Vienna, where I code, create, and occasionally break things (for science!)",
    description:
      "I've worked across a range of environments, from IT support to software engineering at Infineon and the Austrian Postal Service, and now as a Software Architect at SIMStation. I studied software engineering and business management at Technical University Graz, which helps me bridge technical decisions with real-world constraints. I care about pragmatic architecture, clean interfaces, and helping teams move fast without breaking things. Don't hesitate to reach out.",
  },

  projects: [
    {
      title: "TapToQR",
      description:
        "Browser Extension to instantly generate and share a QR code for the webpage you're currently viewing, making link sharing seamless and quick.",
      logo: "https://cdn.jsdelivr.net/npm/programming-languages-logos/src/javascript/javascript.png",
      linkText: "View Project",
      link: "https://taptoqr.moritzreis.dev/",
    },
    {
      title: "StatusSwift",
      description:
        "StatusSwift keeps your status in chat applications like Discord and Microsoft Teams set to 'available', preventing automatic changes to 'away' due to inactivity.",
      logo: "https://cdn.jsdelivr.net/npm/programming-languages-logos/src/csharp/csharp.png",
      linkText: "View Project",
      link: "https://github.com/clFaster/StatusSwift",
    },
    {
      title: "TeilFair",
      description:
        "Split expenses fairly with friends. Track shared costs, see who owes whom, and settle up easily. No sign-up required.",
      logo: "https://teilfair.moritzreis.dev/teilfair-logo.svg",
      linkText: "View Project",
      link: "https://teilfair.moritzreis.dev/",
    },
    {
      title: "SVNPathCopy",
      description:
        "Windows Context Menu extension - lets you copy SVN path with revision number.",
      logo: "https://cdn.jsdelivr.net/npm/programming-languages-logos/src/csharp/csharp.png",
      linkText: "View Project",
      link: "https://github.com/clFaster/SVNPathCopy",
    },
    {
      title: "Badge-Generator",
      description: "Python script to generate Event Badges.",
      logo: "https://cdn.jsdelivr.net/npm/programming-languages-logos/src/python/python.png",
      linkText: "View Project",
      link: "https://github.com/clFaster/Badge-Generator",
    },
    {
      title: "AutoGeneratedApi",
      description:
        "The project's objective is to streamline the integration of a React application with a .NET API. ",
      logo: "https://cdn.jsdelivr.net/npm/programming-languages-logos/src/typescript/typescript.png",
      linkText: "View Project",
      link: "https://github.com/clFaster/AutoGeneratedApi",
    },
  ],
};

export default DATA;
